import { getTranslations } from "next-intl/server";
import type { Metadata } from "next";
import { ApplyWizard } from "@/components/apply/apply-wizard";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("Apply.meta");
  return {
    title: t("title"),
    description: t("description"),
  };
}

export default async function ApplyPage() {
  const t = await getTranslations("Apply");

  const labels = {
    sidebar: {
      title: t("sidebar.title"),
      stepOf: t.raw("sidebar.stepOf"),
      steps: {
        countryRegion: t("sidebar.steps.countryRegion"),
        arrivalDate: t("sidebar.steps.arrivalDate"),
        personalInfo: t("sidebar.steps.personalInfo"),
        passportDetails: t("sidebar.steps.passportDetails"),
        review: t("sidebar.steps.review"),
        payment: t("sidebar.steps.payment"),
      },
    },
    step1: {
      number: t("step1.number"),
      title: t("step1.title"),
      subtitle: t("step1.subtitle"),
      nationality: t("step1.nationality"),
      nationalityPlaceholder: t("step1.nationalityPlaceholder"),
      documentType: t("step1.documentType"),
      documentTypePlaceholder: t("step1.documentTypePlaceholder"),
      docOrdinary: t("step1.docOrdinary"),
      docOfficial: t("step1.docOfficial"),
      docDiplomatic: t("step1.docDiplomatic"),
      docEmergency: t("step1.docEmergency"),
      next: t("step1.next"),
    },
    step2: {
      number: t("step2.number"),
      title: t("step2.title"),
      subtitle: t("step2.subtitle"),
      arrivalDate: t("step2.arrivalDate"),
      purposeOfVisit: t("step2.purposeOfVisit"),
      purposePlaceholder: t("step2.purposePlaceholder"),
      purposeTourism: t("step2.purposeTourism"),
      purposeBusiness: t("step2.purposeBusiness"),
      purposeTransit: t("step2.purposeTransit"),
      purposeEducation: t("step2.purposeEducation"),
      purposeMedical: t("step2.purposeMedical"),
      back: t("step2.back"),
      next: t("step2.next"),
    },
    step3: {
      number: t("step3.number"),
      title: t("step3.title"),
      subtitle: t("step3.subtitle"),
      firstName: t("step3.firstName"),
      firstNamePlaceholder: t("step3.firstNamePlaceholder"),
      surname: t("step3.surname"),
      surnamePlaceholder: t("step3.surnamePlaceholder"),
      otherNames: t("step3.otherNames"),
      otherNamesPlaceholder: t("step3.otherNamesPlaceholder"),
      dateOfBirth: t("step3.dateOfBirth"),
      countryOfBirth: t("step3.countryOfBirth"),
      countryOfBirthPlaceholder: t("step3.countryOfBirthPlaceholder"),
      placeOfBirth: t("step3.placeOfBirth"),
      placeOfBirthPlaceholder: t("step3.placeOfBirthPlaceholder"),
      sex: t("step3.sex"),
      sexPlaceholder: t("step3.sexPlaceholder"),
      sexMale: t("step3.sexMale"),
      sexFemale: t("step3.sexFemale"),
      occupation: t("step3.occupation"),
      occupationPlaceholder: t("step3.occupationPlaceholder"),
      occupationEmployed: t("step3.occupationEmployed"),
      occupationSelfEmployed: t("step3.occupationSelfEmployed"),
      occupationStudent: t("step3.occupationStudent"),
      occupationRetired: t("step3.occupationRetired"),
      occupationUnemployed: t("step3.occupationUnemployed"),
      occupationGovernment: t("step3.occupationGovernment"),
      occupationMilitary: t("step3.occupationMilitary"),
      occupationHealthcare: t("step3.occupationHealthcare"),
      occupationTeacher: t("step3.occupationTeacher"),
      occupationOther: t("step3.occupationOther"),
      mobileNumber: t("step3.mobileNumber"),
      mobileNumberPlaceholder: t("step3.mobileNumberPlaceholder"),
      address: t("step3.address"),
      addressPlaceholder: t("step3.addressPlaceholder"),
      email: t("step3.email"),
      emailPlaceholder: t("step3.emailPlaceholder"),
      emailNote: t("step3.emailNote"),
      back: t("step3.back"),
      next: t("step3.next"),
    },
    step4: {
      number: t("step4.number"),
      title: t("step4.title"),
      subtitle: t("step4.subtitle"),
      passportNumber: t("step4.passportNumber"),
      passportNumberPlaceholder: t("step4.passportNumberPlaceholder"),
      passportIssueDate: t("step4.passportIssueDate"),
      passportExpiryDate: t("step4.passportExpiryDate"),
      passportCopyTitle: t("step4.passportCopyTitle"),
      passportCopyDesc: t("step4.passportCopyDesc"),
      passportCopyWarning: t("step4.passportCopyWarning"),
      passportCopyDrop: t("step4.passportCopyDrop"),
      addressInAzerbaijan: t("step4.addressInAzerbaijan"),
      addressInAzerbaijanPlaceholder: t("step4.addressInAzerbaijanPlaceholder"),
      back: t("step4.back"),
      next: t("step4.next"),
    },
    step5: {
      number: t("step5.number"),
      title: t("step5.title"),
      subtitle: t("step5.subtitle"),
      countryRegionTitle: t("step5.countryRegionTitle"),
      arrivalDateTitle: t("step5.arrivalDateTitle"),
      personalTitle: t("step5.personalTitle"),
      passportTitle: t("step5.passportTitle"),
      edit: t("step5.edit"),
      nationality: t("step5.nationality"),
      documentType: t("step5.documentType"),
      arrivalDate: t("step5.arrivalDate"),
      purposeOfVisit: t("step5.purposeOfVisit"),
      fullName: t("step5.fullName"),
      dateOfBirth: t("step5.dateOfBirth"),
      countryOfBirth: t("step5.countryOfBirth"),
      sex: t("step5.sex"),
      occupation: t("step5.occupation"),
      email: t("step5.email"),
      passportNumber: t("step5.passportNumber"),
      passportIssueDate: t("step5.passportIssueDate"),
      passportExpiryDate: t("step5.passportExpiryDate"),
      uploadedDoc: t("step5.uploadedDoc"),
      addressInAzerbaijan: t("step5.addressInAzerbaijan"),
      declarationLabel: t("step5.declarationLabel"),
      back: t("step5.back"),
      next: t("step5.next"),
    },
    step6: {
      number: t("step6.number"),
      title: t("step6.title"),
      subtitle: t("step6.subtitle"),
      portalTitle: t("step6.portalTitle"),
      cardTab: t("step6.cardTab"),
      paypalTab: t("step6.paypalTab"),
      cardName: t("step6.cardName"),
      cardNamePlaceholder: t("step6.cardNamePlaceholder"),
      cardNumber: t("step6.cardNumber"),
      cardNumberPlaceholder: t("step6.cardNumberPlaceholder"),
      cardExpiry: t("step6.cardExpiry"),
      cardExpiryPlaceholder: t("step6.cardExpiryPlaceholder"),
      cardCvv: t("step6.cardCvv"),
      cardCvvPlaceholder: t("step6.cardCvvPlaceholder"),
      agreementLabel: t("step6.agreementLabel"),
      orderTitle: t("step6.orderTitle"),
      visaFeeLabel: t("step6.visaFeeLabel"),
      serviceFeeLabel: t("step6.serviceFeeLabel"),
      totalLabel: t("step6.totalLabel"),
      supportText: t("step6.supportText"),
      back: t("step6.back"),
      submit: t("step6.submit"),
    },
    validation: {
      required: t("validation.required"),
      email: t("validation.email"),
      passportFormat: t("validation.passportFormat"),
      fileRequired: t("validation.fileRequired"),
      fileSize: t("validation.fileSize"),
      fileType: t("validation.fileType"),
      declarationRequired: t("validation.declarationRequired"),
      paymentAgreementRequired: t("validation.paymentAgreementRequired"),
    },
  };

  return (
    <main className="min-h-screen bg-[#F8F9FA] py-10 px-4">
      <div className="max-w-5xl mx-auto">
        <ApplyWizard labels={labels} />
      </div>
    </main>
  );
}
